import { useState } from 'react';
import axios from 'axios';
import { toast } from 'sonner';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, MenuItem, Select, Stack, Switch, TextField } from '@mui/material';
import { useCreatePipelineStage, useUpdatePipelineStage } from '../hooks/usePipelineConfig';
import type { PipelineStageConfig, TerminalType } from '../types/pipelineConfig.types';
const terminals: TerminalType[] = ['NONE', 'WON', 'LOST', 'ON_HOLD'];
const message = (error: unknown) => axios.isAxiosError<{ message?: string }>(error) ? error.response?.data?.message : undefined;
export default function StageConfigDialog({ stage, open, onClose }: { stage?: PipelineStageConfig | null; open: boolean; onClose: () => void }) { const create = useCreatePipelineStage(); const update = useUpdatePipelineStage(); const [code, setCode] = useState(stage?.code ?? ''); const [label, setLabel] = useState(stage?.label ?? ''); const [description, setDescription] = useState(stage?.description ?? ''); const [sortOrder, setSortOrder] = useState(String(stage?.sortOrder ?? 0)); const [color, setColor] = useState(stage?.color ?? ''); const [active, setActive] = useState(stage?.isActive ?? true); const [terminal, setTerminal] = useState(stage?.isTerminal ?? false); const [terminalType, setTerminalType] = useState<TerminalType>(stage?.terminalType ?? 'NONE'); const [isDefault, setDefault] = useState(stage?.isDefault ?? false); const mutation = stage ? update : create; const error = message(mutation.error);
  const submit = async () => { const common = { label: label.trim(), description: description.trim() || undefined, sortOrder: Number(sortOrder), color: color.trim() || undefined, isActive: active, isTerminal: terminal, terminalType: terminal ? terminalType : 'NONE' as TerminalType, isDefault }; try { if (stage) await update.mutateAsync({ id: stage.id, payload: common }); else await create.mutateAsync({ ...common, code: code.trim().toUpperCase().replace(/\s+/g, '_') }); toast.success(stage ? 'مرحله ویرایش شد.' : 'مرحله ایجاد شد.'); onClose(); } catch { toast.error('ذخیره مرحله انجام نشد.'); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{stage ? 'ویرایش مرحله' : 'ایجاد مرحله'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{mutation.isError && <Alert severity="error">{error || 'ذخیره مرحله با خطا مواجه شد.'}</Alert>}<TextField required label="کد مرحله" value={code} disabled={Boolean(stage)} onChange={(e) => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_ ]/g, ''))} helperText="حروف بزرگ، عدد و زیرخط" /><TextField required label="عنوان" value={label} onChange={(e) => setLabel(e.target.value)} /><TextField label="توضیح" multiline value={description} onChange={(e) => setDescription(e.target.value)} /><TextField required type="number" label="ترتیب نمایش" value={sortOrder} onChange={(e) => setSortOrder(e.target.value)} /><TextField label="رنگ" placeholder="#001736" value={color} onChange={(e) => setColor(e.target.value)} /><FormControlLabel label="فعال" control={<Switch checked={active} onChange={(_, v) => setActive(v)} />} /><FormControlLabel label="مرحله پایانی" control={<Switch checked={terminal} onChange={(_, v) => { setTerminal(v); if (!v) setTerminalType('NONE'); }} />} /><FormControl disabled={!terminal}><InputLabel>نوع پایان</InputLabel><Select label="نوع پایان" value={terminalType} onChange={(e) => setTerminalType(e.target.value as TerminalType)}>{terminals.filter((v) => terminal || v === 'NONE').map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</Select></FormControl><FormControlLabel label="مرحله پیش‌فرض" control={<Switch checked={isDefault} onChange={(_, v) => setDefault(v)} />} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>انصراف</Button><Button variant="contained" disabled={mutation.isPending || !label.trim() || (!stage && !code.trim()) || !Number.isFinite(Number(sortOrder)) || (terminal && terminalType === 'NONE')} onClick={submit}>ذخیره</Button></DialogActions></Dialog>;
}
