import { useMemo, useState } from 'react';
import { toast } from 'sonner';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Paper, Stack } from '@mui/material';
import { DataGrid, type GridColDef, type GridRenderCellParams } from '@mui/x-data-grid';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutlineOutlined';
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import { USER_ROLE_LABELS } from '@/features/admin/users/types/adminUser.types';
import { RowActions } from '@/shared/components/RowActions';
import { useDeleteTransitionRule, usePipelineStages, useTransitionRules } from '../hooks/usePipelineConfig';
import type { TransitionRule } from '../types/pipelineConfig.types';
import TransitionRuleDialog from './TransitionRuleDialog';
export default function TransitionRulesTab() { const rules = useTransitionRules(); const stages = usePipelineStages(); const remove = useDeleteTransitionRule(); const [editing, setEditing] = useState<TransitionRule | null>(null); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<TransitionRule | null>(null); const columns = useMemo<GridColDef<TransitionRule>[]>(() => [{ field: 'fromStage', headerName: 'از مرحله', minWidth: 170, valueGetter: (_v, r) => r.fromStage?.label ?? 'هر مرحله / شروع' }, { field: 'toStage', headerName: 'به مرحله', minWidth: 170, valueGetter: (_v, r) => r.toStage?.label ?? r.toStageId }, { field: 'role', headerName: 'نقش', minWidth: 130, valueFormatter: (v) => v ? USER_ROLE_LABELS[v as keyof typeof USER_ROLE_LABELS] ?? v : 'همه نقش‌ها' }, { field: 'allowed', headerName: 'وضعیت', width: 110, valueFormatter: (v) => v ? 'مجاز' : 'مسدود' }, { field: 'actions', headerName: 'عملیات', width: 104, align: 'center', headerAlign: 'center', sortable: false, filterable: false, disableColumnMenu: true, renderCell: ({ row }: GridRenderCellParams<TransitionRule>) => <RowActions actions={[{ key: 'edit', label: 'ویرایش', icon: <EditOutlinedIcon fontSize="small" />, onClick: () => { setEditing(row); setOpen(true); } }, { key: 'delete', label: 'حذف', icon: <DeleteOutlineIcon fontSize="small" />, color: 'error', onClick: () => setDeleting(row) }]} /> }], []); const close = () => { setOpen(false); setEditing(null); }; const confirm = async () => { if (!deleting) return; try { await remove.mutateAsync(deleting.id); toast.success('قانون حذف شد.'); setDeleting(null); } catch { toast.error('حذف قانون انجام نشد.'); } };
  return <Stack spacing={2}><Stack direction="row" sx={{ justifyContent: 'flex-end' }}><Button variant="contained" onClick={() => setOpen(true)}>ایجاد قانون</Button></Stack>{(rules.isError || stages.isError) && <Alert severity="error">دریافت قوانین یا مراحل انجام نشد.</Alert>}<Paper><DataGrid autoHeight rows={rules.data ?? []} columns={columns} loading={rules.isLoading || stages.isLoading} hideFooter /></Paper>{open && <TransitionRuleDialog rule={editing} stages={stages.data ?? []} open onClose={close} />}<Dialog open={Boolean(deleting)} onClose={() => setDeleting(null)}><DialogTitle>حذف قانون انتقال</DialogTitle><DialogContent>این قانون حذف شود؟</DialogContent><DialogActions><Button onClick={() => setDeleting(null)}>انصراف</Button><Button color="error" onClick={confirm}>حذف</Button></DialogActions></Dialog></Stack>;
}
