import { useState } from 'react';
import axios from 'axios';
import { toast } from 'sonner';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack } from '@mui/material';
import { USER_ROLES, USER_ROLE_LABELS, type UserRole } from '@/features/admin/users/types/adminUser.types';
import { useCreateTransitionRule, useUpdateTransitionRule } from '../hooks/usePipelineConfig';
import type { PipelineStageConfig, TransitionRule } from '../types/pipelineConfig.types';
const message = (e: unknown) => axios.isAxiosError<{ message?: string }>(e) ? e.response?.data?.message : undefined;
export default function TransitionRuleDialog({ rule, stages, open, onClose }: { rule: TransitionRule | null; stages: PipelineStageConfig[]; open: boolean; onClose: () => void }) { const create = useCreateTransitionRule(); const update = useUpdateTransitionRule(); const [from, setFrom] = useState(rule?.fromStageId ?? ''); const [to, setTo] = useState(rule?.toStageId ?? ''); const [role, setRole] = useState<UserRole | ''>(rule?.role ?? ''); const [allowed, setAllowed] = useState(rule?.allowed ?? true); const mutation = rule ? update : create; const submit = async () => { const payload = { fromStageId: from || null, toStageId: to, role: role || null, allowed }; try { if (rule) await update.mutateAsync({ id: rule.id, payload }); else await create.mutateAsync(payload); toast.success('قانون انتقال ذخیره شد.'); onClose(); } catch (e) { toast.error(message(e) || 'ذخیره قانون انجام نشد.'); } };
  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{rule ? 'ویرایش قانون انتقال' : 'ایجاد قانون انتقال'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{mutation.isError && <Alert severity="error">{message(mutation.error) || 'ذخیره قانون انجام نشد.'}</Alert>}<FormControl><InputLabel>از مرحله</InputLabel><Select label="از مرحله" value={from} onChange={(e) => setFrom(e.target.value)}><MenuItem value="">هر مرحله / شروع</MenuItem>{stages.map((s) => <MenuItem key={s.id} value={s.id}>{s.label}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>به مرحله</InputLabel><Select label="به مرحله" value={to} onChange={(e) => setTo(e.target.value)}>{stages.map((s) => <MenuItem key={s.id} value={s.id} disabled={s.id === from}>{s.label}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>نقش</InputLabel><Select label="نقش" value={role} onChange={(e) => setRole(e.target.value as UserRole | '')}><MenuItem value="">همه نقش‌ها</MenuItem>{USER_ROLES.map((r) => <MenuItem key={r} value={r}>{USER_ROLE_LABELS[r]}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>وضعیت</InputLabel><Select label="وضعیت" value={allowed ? 'yes' : 'no'} onChange={(e) => setAllowed(e.target.value === 'yes')}><MenuItem value="yes">مجاز</MenuItem><MenuItem value="no">مسدود</MenuItem></Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={onClose}>انصراف</Button><Button variant="contained" disabled={mutation.isPending || !to || from === to} onClick={submit}>ذخیره</Button></DialogActions></Dialog>;
}
