import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Alert, Button, Chip, MenuItem, Paper, Stack, Tab, Tabs, TextField } from '@mui/material';
import { DataGrid, type GridColDef, type GridPaginationModel } from '@mui/x-data-grid';
import AddIcon from '@mui/icons-material/Add';
import { CompanyAutocomplete } from '@/components/companies/CompanyAutocomplete';
import { useCompanyOptionById } from '@/features/companies/hooks/useCompanies';
import { can } from '@/features/auth/utils/permissions'; import { useAuthStore } from '@/store/authStore';
import { PageContainer, PageHeader } from '@/shared/components/ui'; import { JalaliDateRangePicker } from '@/shared/components/JalaliDateField'; import { formatJalaliDateTime } from '@/shared/utils/jalaliDate'; import { getApiErrorMessage } from '@/lib/apiResponse';
import { useMeetings } from '../hooks/useMeetings'; import type { FindMeetingsParams, Meeting, MeetingMode, MeetingStatus } from '../types/meeting.types'; import { meetingModeLabel, meetingModeOptions, meetingStatusColor, meetingStatusLabel, meetingStatusOptions } from '../utils/meetingDisplay'; import MeetingFormDialog from '../components/MeetingFormDialog';

type Quick = 'all' | 'today' | 'upcoming' | 'past' | 'completed' | 'cancelled' | 'mine';
export default function MeetingsPage() { const user = useAuthStore((s) => s.user); const allowed = can(user, 'meeting:view'); const navigate = useNavigate(); const [sp, setSp] = useSearchParams(); const [createOpen, setCreateOpen] = useState(false);
  const page = Math.max(1, Number(sp.get('page')) || 1), limit = [10, 20, 50, 100].includes(Number(sp.get('limit'))) ? Number(sp.get('limit')) : 20; const quick = (sp.get('quick') || 'all') as Quick;
  const set = (values: Record<string, string | undefined>, reset = true) => { const next = new URLSearchParams(sp); Object.entries(values).forEach(([k, v]) => v ? next.set(k, v) : next.delete(k)); if (reset) next.set('page', '1'); setSp(next); };
  const today = new Date(); const todayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate()).toISOString(); const todayEnd = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 59, 59, 999).toISOString();
  const params: FindMeetingsParams = { page, limit, search: sp.get('search') || undefined, companyId: sp.get('companyId') || undefined, opportunityId: sp.get('opportunityId') || undefined, organizerId: sp.get('organizerId') || undefined, assignedUserId: sp.get('assignedUserId') || undefined, status: (sp.get('status') || undefined) as MeetingStatus | undefined, mode: (sp.get('mode') || undefined) as MeetingMode | undefined, dateFrom: quick === 'today' ? todayStart : sp.get('dateFrom') || undefined, dateTo: quick === 'today' ? todayEnd : sp.get('dateTo') || undefined, upcoming: quick === 'upcoming' || undefined, past: quick === 'past' || undefined, mine: quick === 'mine' || undefined };
  if (quick === 'completed') params.status = 'COMPLETED'; if (quick === 'cancelled') params.status = 'CANCELLED'; const query = useMeetings(params, allowed);
  const selectedCompany = useCompanyOptionById(sp.get('companyId') || undefined, allowed);
  const columns: GridColDef<Meeting>[] = [{ field: 'title', headerName: 'عنوان جلسه', flex: 1, minWidth: 180 }, { field: 'company', headerName: 'شرکت', minWidth: 150, valueGetter: (_v, r) => r.company?.brandName || r.company?.legalName || '—' }, { field: 'opportunity', headerName: 'فرصت', minWidth: 150, valueGetter: (_v, r) => r.opportunity?.title || '—' }, { field: 'startAt', headerName: 'زمان شروع', minWidth: 155, valueFormatter: (v) => formatJalaliDateTime(v) }, { field: 'endAt', headerName: 'زمان پایان', minWidth: 155, valueFormatter: (v) => formatJalaliDateTime(v) }, { field: 'mode', headerName: 'نوع برگزاری', width: 110, valueFormatter: (v) => meetingModeLabel(v) }, { field: 'organizer', headerName: 'برگزارکننده', minWidth: 140, valueGetter: (_v, r) => r.organizer?.fullName || '—' }, { field: 'assignees', headerName: 'مسئولان', minWidth: 170, valueGetter: (_v, r) => r.assignees?.map((x) => x.user.fullName).join('، ') || '—' }, { field: 'reminderAt', headerName: 'زمان یادآوری', minWidth: 155, valueFormatter: (v) => v ? formatJalaliDateTime(v) : '—' }, { field: 'status', headerName: 'وضعیت', width: 145, renderCell: (p) => <Chip size="small" label={meetingStatusLabel(p.value)} color={meetingStatusColor(p.value)} /> }, { field: 'actions', headerName: 'عملیات', width: 100, sortable: false, renderCell: (p) => <Button size="small" onClick={() => navigate(`/meetings/${p.row.id}`)}>مشاهده</Button> }];
  const pagination = (m: GridPaginationModel) => set({ page: String(m.page + 1), limit: String(m.pageSize) }, false);
  if (!allowed) return <Alert severity="warning">دسترسی مشاهده جلسات فعال نیست.</Alert>;
  return <PageContainer><PageHeader title="جلسات" description="مدیریت جلسات سازمان" actions={can(user, 'meeting:create') ? <Button variant="contained" startIcon={<AddIcon />} onClick={() => setCreateOpen(true)}>جلسه جدید</Button> : undefined} />
    <Paper sx={{ mb: 2 }}><Tabs value={quick} onChange={(_, v) => set({ quick: v === 'all' ? undefined : v })} variant="scrollable" scrollButtons="auto"><Tab value="all" label="همه" /><Tab value="today" label="جلسات امروز" /><Tab value="upcoming" label="جلسات پیش‌رو" /><Tab value="past" label="جلسات گذشته" /><Tab value="completed" label="برگزارشده" /><Tab value="cancelled" label="لغوشده" /><Tab value="mine" label="جلسات من" /></Tabs></Paper>
    <Paper sx={{ p: 2, mb: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField fullWidth label="جستجو" value={sp.get('search') || ''} onChange={(e) => set({ search: e.target.value || undefined })} /><CompanyAutocomplete value={selectedCompany.data ?? null} onChange={(value) => set({ companyId: value?.id, opportunityId: undefined })} label="شرکت" /><TextField select fullWidth label="وضعیت" value={sp.get('status') || ''} onChange={(e) => set({ status: e.target.value || undefined, quick: undefined })}><MenuItem value="">همه</MenuItem>{meetingStatusOptions.map((x) => <MenuItem key={x.value} value={x.value}>{x.label}</MenuItem>)}</TextField><TextField select fullWidth label="نوع برگزاری" value={sp.get('mode') || ''} onChange={(e) => set({ mode: e.target.value || undefined })}><MenuItem value="">همه</MenuItem>{meetingModeOptions.map((x) => <MenuItem key={x.value} value={x.value}>{x.label}</MenuItem>)}</TextField><JalaliDateRangePicker fullWidth label="بازه تاریخ" startValue={sp.get('dateFrom')} endValue={sp.get('dateTo')} onChange={(r) => set({ dateFrom: r.start, dateTo: r.end, quick: undefined })} /></Stack></Paper>
    {query.isError && <Alert severity="error" sx={{ mb: 2 }}>{getApiErrorMessage(query.error, 'خطا در دریافت جلسات')}</Alert>}
    <Paper sx={{ width: '100%', overflow: 'hidden' }}><DataGrid autoHeight rows={query.data?.data ?? []} columns={columns} loading={query.isFetching} rowCount={query.data?.meta.total ?? 0} paginationMode="server" paginationModel={{ page: page - 1, pageSize: limit }} onPaginationModelChange={pagination} pageSizeOptions={[10, 20, 50, 100]} disableRowSelectionOnClick localeText={{ noRowsLabel: sp.get('search') ? 'جلسه‌ای مطابق جستجو یافت نشد.' : 'جلسه‌ای ثبت نشده است.' }} sx={{ minWidth: 1100 }} /></Paper>
    {createOpen && <MeetingFormDialog key="create-meeting" open onClose={() => setCreateOpen(false)} />}</PageContainer>;
}
