import { useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField } from '@mui/material';
import { DataGrid, type GridColDef, type GridPaginationModel } from '@mui/x-data-grid';
import { JalaliDateRangePicker } from '@/shared/components/JalaliDateField';
import { formatJalaliDateTime } from '@/shared/utils/jalaliDate';
import { formatIrrPrice } from '@/features/opportunityLineItems/utils/money';
import { useProductPriceHistory } from '../hooks/useProductCatalog';
import type { ProductCatalogItem, ProductPriceHistory, ProductPriceHistoryReason } from '../types/productCatalog.types';

const reasons: Record<ProductPriceHistoryReason, string> = { MIGRATION_BASELINE: 'وضعیت اولیه ثبت تاریخچه', PRODUCT_CREATED: 'ایجاد محصول', PRODUCT_UPDATED: 'ویرایش قیمت محصول', EXCHANGE_RATE_CHANGED: 'تغییر نرخ دلار', MANUAL_RECALCULATION: 'محاسبه مجدد دستی' };
export default function ProductPriceHistoryDialog({ product, onClose }: { product: ProductCatalogItem; onClose: () => void }) {
  const [pagination, setPagination] = useState<GridPaginationModel>({ page: 0, pageSize: 20 }); const [reason, setReason] = useState<ProductPriceHistoryReason | ''>(''); const [range, setRange] = useState<{ start?: string; end?: string }>({});
  const query = useProductPriceHistory(product.id, { page: pagination.page + 1, limit: pagination.pageSize, reason: reason || undefined, dateFrom: range.start, dateTo: range.end });
  const columns: GridColDef<ProductPriceHistory>[] = [{ field: 'validFrom', headerName: 'شروع اعتبار', minWidth: 150, valueFormatter: formatJalaliDateTime }, { field: 'validTo', headerName: 'پایان اعتبار', minWidth: 150, valueFormatter: (v) => v ? formatJalaliDateTime(v) : 'تاکنون' }, { field: 'reason', headerName: 'دلیل تغییر', minWidth: 190, valueFormatter: (v) => reasons[v as ProductPriceHistoryReason] ?? String(v) }, { field: 'pricingCurrency', headerName: 'ارز ورود', width: 100 }, { field: 'inPersonInputPrice', headerName: 'ورودی حضوری', minWidth: 150 }, { field: 'inPersonProfitPercent', headerName: 'سود حضوری', width: 110, valueFormatter: (v) => v == null ? '—' : `${v}٪` }, { field: 'inPersonPriceIrr', headerName: 'نهایی حضوری', minWidth: 160, valueFormatter: formatIrrPrice }, { field: 'digikalaInputPrice', headerName: 'ورودی دیجی‌کالا', minWidth: 160 }, { field: 'digikalaProfitPercent', headerName: 'سود دیجی‌کالا', width: 120, valueFormatter: (v) => v == null ? '—' : `${v}٪` }, { field: 'digikalaPriceIrr', headerName: 'نهایی دیجی‌کالا', minWidth: 170, valueFormatter: formatIrrPrice }, { field: 'exchangeRateValueSnapshot', headerName: 'نرخ دلار', minWidth: 150, valueFormatter: (v) => v == null ? '—' : formatIrrPrice(v) }, { field: 'changedBy', headerName: 'ثبت‌کننده', minWidth: 150, valueGetter: (_v, r) => r.changedBy?.fullName ?? 'سیستم' }, { field: 'note', headerName: 'توضیحات', minWidth: 180, valueFormatter: (v) => v || '—' }];
  return <Dialog open onClose={onClose} fullWidth maxWidth="xl"><DialogTitle>تاریخچه قیمت — {product.name}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Alert severity="info">سوابق قبل از فعال‌شدن تاریخچه قیمت در سیستم قابل بازسازی نیستند.</Alert><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField select fullWidth label="دلیل تغییر" value={reason} onChange={(e) => { setReason(e.target.value as ProductPriceHistoryReason | ''); setPagination((p) => ({ ...p, page: 0 })); }}><MenuItem value="">همه</MenuItem>{Object.entries(reasons).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><JalaliDateRangePicker fullWidth label="بازه تاریخ شروع اعتبار" startValue={range.start} endValue={range.end} onChange={(r) => { setRange(r); setPagination((p) => ({ ...p, page: 0 })); }} /></Stack>{query.isError && <Alert severity="error" action={<Button onClick={() => query.refetch()}>تلاش مجدد</Button>}>دریافت تاریخچه قیمت انجام نشد.</Alert>}<DataGrid autoHeight rows={query.data?.data ?? []} columns={columns} loading={query.isFetching} rowCount={query.data?.meta.total ?? 0} paginationMode="server" paginationModel={pagination} onPaginationModelChange={setPagination} pageSizeOptions={[10, 20, 50, 100]} disableRowSelectionOnClick localeText={{ noRowsLabel: 'سابقه قیمتی ثبت نشده است.' }} sx={{ minWidth: 1700 }} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>بستن</Button></DialogActions></Dialog>;
}
