import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { pipelineConfigService } from '../services/pipelineConfig.service';
import type { CreatePipelineStagePayload, ReorderStagesPayload, TransitionRulePayload, UpdatePipelineStagePayload } from '../types/pipelineConfig.types';
export const pipelineConfigQueryKeys = { all: ['pipeline-config'] as const, stages: () => ['pipeline-stages'] as const, rules: () => ['pipeline-transitions'] as const };
export function usePipelineStages(enabled = true) { return useQuery({ queryKey: pipelineConfigQueryKeys.stages(), queryFn: pipelineConfigService.getStages, enabled, staleTime: 60_000 }); }
export function useTransitionRules(enabled = true) { return useQuery({ queryKey: pipelineConfigQueryKeys.rules(), queryFn: pipelineConfigService.getTransitionRules, enabled, staleTime: 60_000 }); }
function useInvalidateAll() { const c = useQueryClient(); return () => Promise.all([c.invalidateQueries({ queryKey: pipelineConfigQueryKeys.stages() }), c.invalidateQueries({ queryKey: pipelineConfigQueryKeys.rules() }), c.invalidateQueries({ queryKey: ['pipeline'] }), c.invalidateQueries({ queryKey: ['opportunities'] }), c.invalidateQueries({ queryKey: ['reports'] })]); }
export function useCreatePipelineStage() { const invalidate = useInvalidateAll(); return useMutation({ mutationFn: (p: CreatePipelineStagePayload) => pipelineConfigService.createStage(p), onSuccess: invalidate }); }
export function useUpdatePipelineStage() { const invalidate = useInvalidateAll(); return useMutation({ mutationFn: ({ id, payload }: { id: string; payload: UpdatePipelineStagePayload }) => pipelineConfigService.updateStage(id, payload), onSuccess: invalidate }); }
export function useDeactivatePipelineStage() { const invalidate = useInvalidateAll(); return useMutation({ mutationFn: ({ id, replacementStageId }: { id: string; replacementStageId?: string }) => pipelineConfigService.deactivateStage(id, replacementStageId), onSuccess: invalidate }); }
export function useReorderPipelineStages() { const invalidate = useInvalidateAll(); return useMutation({ mutationFn: (p: ReorderStagesPayload) => pipelineConfigService.reorderStages(p), onSuccess: invalidate }); }
function useInvalidateRules() { const invalidate = useInvalidateAll(); return invalidate; }
export function useCreateTransitionRule() { const invalidate = useInvalidateRules(); return useMutation({ mutationFn: (p: TransitionRulePayload) => pipelineConfigService.createTransitionRule(p), onSuccess: invalidate }); }
export function useUpdateTransitionRule() { const invalidate = useInvalidateRules(); return useMutation({ mutationFn: ({ id, payload }: { id: string; payload: TransitionRulePayload }) => pipelineConfigService.updateTransitionRule(id, payload), onSuccess: invalidate }); }
export function useDeleteTransitionRule() { const invalidate = useInvalidateRules(); return useMutation({ mutationFn: pipelineConfigService.deleteTransitionRule, onSuccess: invalidate }); }
