import { useState } from 'react';
import { toast } from 'sonner';
import { Alert, Button, Checkbox, FormControl, FormControlLabel, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import { can } from '@/features/auth/utils/permissions'; import { useAuthStore } from '@/store/authStore';
import { USER_ROLES, USER_ROLE_LABELS } from '../../users/types/adminUser.types'; import type { UserRole } from '../../users/types/adminUser.types';
import { KNOWN_PERMISSION_ACTIONS } from '../types/adminPermission.types';
import { useAssignPermission, useBulkAssignPermissions, useBulkRevokePermissions, useCreatePermission, useRevokePermission } from '../hooks/useAdminPermissions';

export default function AdminPermissionsPage() {
  const user = useAuthStore((s) => s.user); const allowed = can(user, 'permission:manage', ['ADMIN']); const [role, setRole] = useState<UserRole>('REP'); const [action, setAction] = useState<string>(KNOWN_PERMISSION_ACTIONS[0]); const [selected, setSelected] = useState<string[]>([]); const [newAction, setNewAction] = useState(''); const [description, setDescription] = useState('');
  const assign = useAssignPermission(); const revoke = useRevokePermission(); const bulkAssign = useBulkAssignPermissions(); const bulkRevoke = useBulkRevokePermissions(); const create = useCreatePermission(); const pending = assign.isPending || revoke.isPending || bulkAssign.isPending || bulkRevoke.isPending || create.isPending;
  if (!allowed) return <Alert severity="warning">شما دسترسی مدیریت مجوزها را ندارید.</Alert>;
  const run = async (kind: 'assign' | 'revoke' | 'bulkAssign' | 'bulkRevoke') => { try { if (kind === 'assign') await assign.mutateAsync({ role, action }); if (kind === 'revoke') await revoke.mutateAsync({ role, action }); if (kind === 'bulkAssign') await bulkAssign.mutateAsync({ role, actions: selected }); if (kind === 'bulkRevoke') await bulkRevoke.mutateAsync({ role, actions: selected }); toast.success(kind.includes('bulk') ? 'عملیات گروهی مجوزها با موفقیت انجام شد.' : kind === 'assign' ? 'مجوز با موفقیت تخصیص داده شد.' : 'مجوز با موفقیت حذف شد.'); } catch { toast.error('عملیات مجوز با خطا مواجه شد.'); } };
  const createPermission = async () => { if (!/^[a-z0-9-]+:[a-z0-9-]+$/i.test(newAction.trim())) { toast.error('کلید مجوز باید مانند resource:action باشد.'); return; } try { await create.mutateAsync({ action: newAction.trim(), description: description.trim() || undefined }); toast.success('مجوز با موفقیت ایجاد شد.'); setNewAction(''); setDescription(''); } catch { toast.error('خطا در ایجاد مجوز.'); } };
  return <Stack spacing={3}><div><Typography variant="h4">مدیریت مجوزها</Typography><Typography color="text.secondary">مدیریت دسترسی نقش‌ها به قابلیت‌های سیستم.</Typography></div><Alert severity="info">بک‌اند فعلی endpoint مشاهده وضعیت مجوزهای نقش‌ها را ارائه نمی‌دهد؛ فقط امکان تخصیص یا حذف مجوز وجود دارد.</Alert>
    <Paper sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">تخصیص یا حذف مجوز</Typography><FormControl><InputLabel id="permission-role">نقش</InputLabel><Select labelId="permission-role" label="نقش" value={role} onChange={(e) => setRole(e.target.value as UserRole)}>{USER_ROLES.map((item) => <MenuItem key={item} value={item}>{USER_ROLE_LABELS[item]}</MenuItem>)}</Select></FormControl><FormControl><InputLabel id="permission-action">مجوز</InputLabel><Select labelId="permission-action" label="مجوز" value={action} onChange={(e) => setAction(e.target.value)}>{KNOWN_PERMISSION_ACTIONS.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl><Stack direction="row" spacing={1}><Button variant="contained" onClick={() => run('assign')} disabled={pending}>تخصیص مجوز</Button><Button color="error" onClick={() => run('revoke')} disabled={pending}>حذف مجوز</Button></Stack></Stack></Paper>
    <Paper sx={{ p: 2 }}><Stack spacing={1}><Typography variant="h6">عملیات گروهی</Typography><Stack direction="row" sx={{ flexWrap: 'wrap' }}>{KNOWN_PERMISSION_ACTIONS.map((item) => <FormControlLabel key={item} label={item} control={<Checkbox checked={selected.includes(item)} onChange={(_, checked) => setSelected((value) => checked ? [...value, item] : value.filter((entry) => entry !== item))} />} />)}</Stack><Stack direction="row" spacing={1}><Button variant="contained" onClick={() => run('bulkAssign')} disabled={!selected.length || pending}>تخصیص گروهی</Button><Button color="error" onClick={() => run('bulkRevoke')} disabled={!selected.length || pending}>حذف گروهی</Button></Stack></Stack></Paper>
    <Paper sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">ایجاد مجوز</Typography><TextField label="کلید مجوز" placeholder="resource:action" value={newAction} onChange={(e) => setNewAction(e.target.value)} /><TextField label="توضیح" multiline minRows={2} value={description} onChange={(e) => setDescription(e.target.value)} /><Button variant="contained" onClick={createPermission} disabled={!newAction.trim() || pending}>ایجاد مجوز</Button></Stack></Paper>
  </Stack>;
}
