import { useMemo, useState, type UIEvent } from 'react';
import { useInfiniteQuery } from '@tanstack/react-query';
import { Alert, Autocomplete, Box, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, ListItemText, MenuItem, Select, Stack, TextField } from '@mui/material';
import { toast } from 'sonner';
import { CompanyAutocomplete } from '@/components/companies/CompanyAutocomplete';
import type { CompanyOption } from '@/features/companies/types/company.types';
import { useDebouncedValue } from '@/features/companies/hooks/useDebouncedValue';
import { opportunitiesService } from '@/features/opportunities/services/opportunities.service';
import type { Opportunity } from '@/features/opportunities/types/opportunity.types';
import { peopleService } from '@/features/people/services/people.service';
import type { DirectoryPerson } from '@/features/people/types/person.types';
import { JalaliDateTimePicker } from '@/shared/components/JalaliDateField';
import { getApiErrorMessage } from '@/lib/apiResponse';
import { useAssigneeOptions, useCreateMeeting, useUpdateMeeting } from '../hooks/useMeetings';
import type { AssigneeOption, Meeting, MeetingMode } from '../types/meeting.types';
import { meetingModeOptions } from '../utils/meetingDisplay';

type ReminderPreset = 'none' | '15' | '30' | '60' | '120' | '1440' | 'custom';
const reminderOptions: { value: ReminderPreset; label: string }[] = [{ value: 'none', label: 'بدون یادآوری' }, { value: '15', label: '۱۵ دقیقه قبل' }, { value: '30', label: '۳۰ دقیقه قبل' }, { value: '60', label: '۱ ساعت قبل' }, { value: '120', label: '۲ ساعت قبل' }, { value: '1440', label: '۱ روز قبل' }, { value: 'custom', label: 'زمان دلخواه' }];
const unique = <T extends { id: string }>(values: T[]) => Array.from(new Map(values.map((x) => [x.id, x])).values());
const loadMore = (event: UIEvent<HTMLElement>, hasNext: boolean | undefined, fetching: boolean, fetch: () => unknown) => { const el = event.currentTarget; if (el.scrollHeight - el.scrollTop - el.clientHeight < 80 && hasNext && !fetching) fetch(); };
const companyFromMeeting = (meeting?: Meeting): CompanyOption | null => meeting?.company ? { id: meeting.company.id, legalName: meeting.company.legalName, brandName: meeting.company.brandName } : null;

export interface MeetingFormDialogProps { open: boolean; onClose: () => void; meeting?: Meeting; initialCompany?: CompanyOption | null; initialOpportunity?: Opportunity | null; lockCompany?: boolean }

export default function MeetingFormDialog({ open, onClose, meeting, initialCompany, initialOpportunity, lockCompany = false }: MeetingFormDialogProps) {
  const [company, setCompany] = useState<CompanyOption | null>(() => companyFromMeeting(meeting) ?? initialCompany ?? null);
  const [opportunity, setOpportunity] = useState<Opportunity | null>(() => meeting?.opportunity ? { ...meeting.opportunity, stageId: '', stage: { id: '', code: '', label: '', sortOrder: 0 }, priority: 'MEDIUM', createdAt: '', updatedAt: '' } : initialOpportunity ?? null);
  const [title, setTitle] = useState(meeting?.title ?? ''); const [agenda, setAgenda] = useState(meeting?.agenda ?? ''); const [description, setDescription] = useState(meeting?.description ?? '');
  const [mode, setMode] = useState<MeetingMode>(meeting?.mode ?? 'IN_PERSON'); const [location, setLocation] = useState(meeting?.location ?? ''); const [meetingUrl, setMeetingUrl] = useState(meeting?.meetingUrl ?? '');
  const [startAt, setStartAt] = useState(meeting?.startAt ?? ''); const [endAt, setEndAt] = useState(meeting?.endAt ?? '');
  const initialPreset = useMemo<ReminderPreset>(() => { if (!meeting?.reminderAt) return 'none'; const mins = Math.round((new Date(meeting.startAt).getTime() - new Date(meeting.reminderAt).getTime()) / 60000); return ['15', '30', '60', '120', '1440'].includes(String(mins)) ? String(mins) as ReminderPreset : 'custom'; }, [meeting]);
  const [reminderPreset, setReminderPreset] = useState<ReminderPreset>(initialPreset); const [customReminder, setCustomReminder] = useState(meeting?.reminderAt ?? '');
  const [assignees, setAssignees] = useState<AssigneeOption[]>(() => meeting?.assignees?.map((x) => x.user) ?? []); const [attendees, setAttendees] = useState<DirectoryPerson[]>(() => meeting?.attendees?.map((x) => x.person as DirectoryPerson) ?? []);
  const [assigneeSearch, setAssigneeSearch] = useState(''); const debouncedAssignee = useDebouncedValue(assigneeSearch, 400); const assigneeQuery = useAssigneeOptions(debouncedAssignee, open);
  const [opportunitySearch, setOpportunitySearch] = useState(''); const debouncedOpportunity = useDebouncedValue(opportunitySearch, 400);
  const opportunityQuery = useInfiniteQuery({ queryKey: ['meeting-opportunity-options', company?.id, debouncedOpportunity], queryFn: ({ pageParam }) => opportunitiesService.listByCompany(company!.id, { page: pageParam, limit: 50, search: debouncedOpportunity || undefined }), initialPageParam: 1, getNextPageParam: (last) => last.meta.hasNext ? last.meta.page + 1 : undefined, enabled: open && Boolean(company), staleTime: 120000 });
  const [personSearch, setPersonSearch] = useState(''); const debouncedPerson = useDebouncedValue(personSearch, 400);
  const peopleQuery = useInfiniteQuery({ queryKey: ['meeting-person-options', company?.id, debouncedPerson], queryFn: ({ pageParam }) => peopleService.getPeopleDirectory({ page: pageParam, limit: 50, companyId: company!.id, search: debouncedPerson || undefined }), initialPageParam: 1, getNextPageParam: (last) => last.meta.hasNext ? last.meta.page + 1 : undefined, enabled: open && Boolean(company), staleTime: 120000 });
  const create = useCreateMeeting(); const update = useUpdateMeeting(); const pending = create.isPending || update.isPending; const mutationError = create.error || update.error;
  const assigneeOptions = unique([...assignees, ...(assigneeQuery.data?.pages.flatMap((p) => p.data) ?? [])]); const opportunityOptions = unique([...(opportunity ? [opportunity] : []), ...(opportunityQuery.data?.pages.flatMap((p) => p.data) ?? [])]); const peopleOptions = unique([...attendees, ...(peopleQuery.data?.pages.flatMap((p) => p.data) ?? [])]);
  const reminderAt = reminderPreset === 'none' ? undefined : reminderPreset === 'custom' ? customReminder || undefined : startAt ? new Date(new Date(startAt).getTime() - Number(reminderPreset) * 60000).toISOString() : undefined;
  const validation = !company ? 'انتخاب شرکت الزامی است.' : !title.trim() ? 'عنوان جلسه الزامی است.' : !startAt || !endAt ? 'زمان شروع و پایان الزامی است.' : new Date(endAt) <= new Date(startAt) ? 'زمان پایان باید بعد از زمان شروع باشد.' : reminderPreset === 'custom' && !customReminder ? 'زمان یادآوری را انتخاب کنید.' : reminderAt && new Date(reminderAt) >= new Date(startAt) ? 'زمان یادآوری باید قبل از شروع جلسه باشد.' : reminderAt && new Date(startAt) > new Date() && new Date(reminderAt) < new Date() ? 'زمان یادآوری نمی‌تواند در گذشته باشد.' : mode !== 'IN_PERSON' && meetingUrl && !/^https?:\/\//i.test(meetingUrl) ? 'لینک جلسه باید با http یا https شروع شود.' : '';
  const changeCompany = (next: CompanyOption | null) => { if (next?.id === company?.id) return; if ((opportunity || attendees.length) && !window.confirm('با تغییر شرکت، فرصت و مدعوین انتخاب‌شده پاک می‌شوند. ادامه می‌دهید؟')) return; setCompany(next); setOpportunity(null); setAttendees([]); };
  const submit = async () => { if (validation || !company) return; const payload = { companyId: company.id, opportunityId: opportunity?.id || undefined, title: title.trim(), agenda: agenda.trim() || undefined, description: description.trim() || undefined, mode, location: location.trim() || undefined, meetingUrl: meetingUrl.trim() || undefined, startAt: new Date(startAt).toISOString(), endAt: new Date(endAt).toISOString(), reminderAt, assigneeUserIds: assignees.map((x) => x.id), attendeePersonIds: attendees.map((x) => x.id) }; try { if (meeting) await update.mutateAsync({ id: meeting.id, payload }); else await create.mutateAsync(payload); toast.success(meeting ? 'جلسه با موفقیت ویرایش شد.' : 'جلسه با موفقیت ثبت شد.'); onClose(); } catch (error) { toast.error(getApiErrorMessage(error, meeting ? 'ویرایش جلسه انجام نشد.' : 'ثبت جلسه انجام نشد.')); } };
  return <Dialog open={open} onClose={pending ? undefined : onClose} fullWidth maxWidth="md"><DialogTitle>{meeting ? 'ویرایش جلسه' : 'جلسه جدید'}</DialogTitle><DialogContent sx={{ pt: '12px !important' }}><Stack spacing={2}>
    {mutationError && <Alert severity="error">{getApiErrorMessage(mutationError, 'ذخیره جلسه انجام نشد.')}</Alert>}
    <CompanyAutocomplete value={company} onChange={changeCompany} required disabled={lockCompany || pending} />
    <Autocomplete options={opportunityOptions} value={opportunity} disabled={!company || pending} filterOptions={(x) => x} getOptionLabel={(x) => x.title} isOptionEqualToValue={(a, b) => a.id === b.id} onInputChange={(_, v, reason) => setOpportunitySearch(reason === 'input' ? v : '')} onChange={(_, v) => setOpportunity(v)} slotProps={{ listbox: { onScroll: (e) => loadMore(e, opportunityQuery.hasNextPage, opportunityQuery.isFetchingNextPage, () => void opportunityQuery.fetchNextPage()) } }} renderInput={(params) => <TextField {...params} label="فرصت مرتبط" helperText={!company ? 'ابتدا شرکت را انتخاب کنید.' : undefined} />} />
    <TextField label="عنوان جلسه" required value={title} onChange={(e) => setTitle(e.target.value)} /><TextField label="دستور جلسه" multiline minRows={2} value={agenda} onChange={(e) => setAgenda(e.target.value)} /><TextField label="توضیحات" multiline minRows={2} value={description} onChange={(e) => setDescription(e.target.value)} />
    <FormControl><InputLabel>نوع برگزاری</InputLabel><Select label="نوع برگزاری" value={mode} onChange={(e) => setMode(e.target.value as MeetingMode)}>{meetingModeOptions.map((x) => <MenuItem key={x.value} value={x.value}>{x.label}</MenuItem>)}</Select></FormControl>
    {(mode === 'IN_PERSON' || mode === 'HYBRID') && <TextField label="محل جلسه" value={location} onChange={(e) => setLocation(e.target.value)} />}{(mode === 'ONLINE' || mode === 'HYBRID') && <TextField label="لینک جلسه" dir="ltr" value={meetingUrl} onChange={(e) => setMeetingUrl(e.target.value)} />}
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><JalaliDateTimePicker fullWidth required label="تاریخ و ساعت شروع" value={startAt} onChange={(v) => setStartAt(v ?? '')} /><JalaliDateTimePicker fullWidth required label="تاریخ و ساعت پایان" value={endAt} onChange={(v) => setEndAt(v ?? '')} /></Stack>
    <FormControl><InputLabel>زمان یادآوری</InputLabel><Select label="زمان یادآوری" value={reminderPreset} onChange={(e) => setReminderPreset(e.target.value as ReminderPreset)}>{reminderOptions.map((x) => <MenuItem key={x.value} value={x.value}>{x.label}</MenuItem>)}</Select></FormControl>{reminderPreset === 'custom' && <JalaliDateTimePicker fullWidth required label="زمان دلخواه یادآوری" value={customReminder} onChange={(v) => setCustomReminder(v ?? '')} />}
    <Autocomplete multiple options={assigneeOptions} value={assignees} filterOptions={(x) => x} getOptionLabel={(x) => x.fullName || x.email || x.id} isOptionEqualToValue={(a, b) => a.id === b.id} onInputChange={(_, v, reason) => setAssigneeSearch(reason === 'input' ? v : '')} onChange={(_, v) => setAssignees(v)} slotProps={{ listbox: { onScroll: (e) => loadMore(e, assigneeQuery.hasNextPage, assigneeQuery.isFetchingNextPage, () => void assigneeQuery.fetchNextPage()) } }} renderOption={(props, x) => <Box component="li" {...props} key={x.id}><ListItemText primary={x.fullName} secondary={x.email} /></Box>} renderInput={(params) => <TextField {...params} label="مسئولان داخلی" slotProps={{ ...params.slotProps, input: { ...params.slotProps.input, endAdornment: <>{assigneeQuery.isFetching && <CircularProgress size={18} />}{params.slotProps.input.endAdornment}</> } }} />} />
    <Autocomplete multiple options={peopleOptions} value={attendees} disabled={!company} filterOptions={(x) => x} getOptionLabel={(x) => x.fullName} isOptionEqualToValue={(a, b) => a.id === b.id} onInputChange={(_, v, reason) => setPersonSearch(reason === 'input' ? v : '')} onChange={(_, v) => setAttendees(v)} slotProps={{ listbox: { onScroll: (e) => loadMore(e, peopleQuery.hasNextPage, peopleQuery.isFetchingNextPage, () => void peopleQuery.fetchNextPage()) } }} renderOption={(props, x) => <Box component="li" {...props} key={x.id}><ListItemText primary={x.fullName} secondary={x.title || x.jobTitle} /></Box>} renderInput={(params) => <TextField {...params} label="مدعوین شرکت" helperText={!company ? 'ابتدا شرکت را انتخاب کنید.' : undefined} />} />
    {validation && <Alert severity="warning">{validation}</Alert>}
  </Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={pending}>انصراف</Button><Button variant="contained" disabled={pending || Boolean(validation)} onClick={submit}>ذخیره</Button></DialogActions></Dialog>;
}
