import { useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Paper, Stack, TextField, Typography } from '@mui/material';
import { DataGrid, type GridColDef, type GridPaginationModel } from '@mui/x-data-grid';
import { toast } from 'sonner';
import { can } from '@/features/auth/utils/permissions'; import { useAuthStore } from '@/store/authStore'; import { PageContainer, PageHeader } from '@/shared/components/ui'; import { JalaliDateTimePicker } from '@/shared/components/JalaliDateField'; import { formatJalaliDateTime } from '@/shared/utils/jalaliDate'; import { getApiErrorMessage } from '@/lib/apiResponse'; import { formatIrrPrice } from '@/features/opportunityLineItems/utils/money';
import { useCreateExchangeRate, useCurrentExchangeRate, useExchangeRates } from '../hooks/useExchangeRates'; import type { ExchangeRate } from '../types/exchangeRate.types';

export default function ExchangeRatesPage() {
  const user = useAuthStore((state) => state.user), allowed = can(user, 'exchange-rate:view'), manageable = can(user, 'exchange-rate:manage');
  const [pagination, setPagination] = useState<GridPaginationModel>({ page: 0, pageSize: 20 }), [rate, setRate] = useState(''), [effectiveFrom, setEffectiveFrom] = useState(''), [note, setNote] = useState(''), [confirmOpen, setConfirmOpen] = useState(false);
  const current = useCurrentExchangeRate(allowed), history = useExchangeRates(pagination.page + 1, pagination.pageSize, allowed), create = useCreateExchangeRate();
  const valid = /^\d+(\.\d+)?$/.test(rate.replace(/,/g, '')) && Number(rate.replace(/,/g, '')) > 0;
  const submit = async () => { try { const result = await create.mutateAsync({ rate: rate.replace(/,/g, ''), effectiveFrom: effectiveFrom || undefined, note: note.trim() || undefined }); toast.success(`نرخ جدید ثبت شد و قیمت ${result.recalculatedProductCount.toLocaleString('fa-IR')} محصول دلاری مجدداً محاسبه شد.`); setRate(''); setEffectiveFrom(''); setNote(''); setConfirmOpen(false); } catch (error) { toast.error(getApiErrorMessage(error, 'ثبت نرخ دلار انجام نشد.')); } };
  const columns: GridColDef<ExchangeRate>[] = [{ field: 'rate', headerName: 'نرخ دلار به ریال', minWidth: 190, valueFormatter: (value) => formatIrrPrice(value) }, { field: 'validFrom', headerName: 'از تاریخ', minWidth: 170, valueFormatter: (value) => formatJalaliDateTime(value) }, { field: 'validTo', headerName: 'تا تاریخ', minWidth: 170, valueFormatter: (value) => value ? formatJalaliDateTime(value) : 'تاکنون' }, { field: 'status', headerName: 'وضعیت', minWidth: 100, valueFormatter: (value) => value === 'ACTIVE' ? 'فعال' : 'منقضی' }, { field: 'createdBy', headerName: 'ثبت‌کننده', minWidth: 150, valueGetter: (_value, row) => row.createdBy?.fullName || '—' }, { field: 'note', headerName: 'توضیحات', minWidth: 220, flex: 1, valueFormatter: (value) => value || '—' }];
  if (!allowed) return <Alert severity="warning">دسترسی مشاهده نرخ دلار فعال نیست.</Alert>;
  return <PageContainer><PageHeader title="نرخ دلار" description="مدیریت تاریخچه نرخ تبدیل دلار آمریکا به ریال ایران" />
    {current.isLoading ? <Typography>در حال دریافت نرخ فعلی...</Typography> : current.isError ? <Alert severity="error" action={<Button onClick={() => current.refetch()}>تلاش مجدد</Button>}>خطا در دریافت نرخ فعلی دلار</Alert> : current.data ? <Paper sx={{ p: 3, mb: 2 }}><Typography variant="h6" sx={{ mb: 2 }}>نرخ فعلی</Typography><Grid container spacing={2}><Grid size={{ xs: 12, sm: 6, md: 3 }}><Typography color="text.secondary">هر ۱ دلار</Typography><Typography variant="h5">{formatIrrPrice(current.data.rate)}</Typography></Grid><Grid size={{ xs: 12, sm: 6, md: 3 }}><Typography color="text.secondary">تاریخ شروع اعتبار</Typography><Typography>{formatJalaliDateTime(current.data.validFrom)}</Typography></Grid><Grid size={{ xs: 12, sm: 6, md: 3 }}><Typography color="text.secondary">ثبت‌کننده</Typography><Typography>{current.data.createdBy?.fullName || '—'}</Typography></Grid><Grid size={{ xs: 12, sm: 6, md: 3 }}><Typography color="text.secondary">توضیحات</Typography><Typography>{current.data.note || '—'}</Typography></Grid></Grid></Paper> : <Alert severity="warning" sx={{ mb: 2 }}>هنوز نرخ فعال دلار ثبت نشده است.</Alert>}
    {manageable && <Paper sx={{ p: 3, mb: 2 }}><Typography variant="h6" sx={{ mb: 2 }}>ثبت نرخ جدید</Typography><Stack spacing={2}><TextField required label="هر ۱ دلار چند ریال است" value={rate} onChange={(e) => setRate(e.target.value)} helperText={!rate || valid ? undefined : 'نرخ باید عددی بزرگ‌تر از صفر باشد.'} error={Boolean(rate) && !valid} /><JalaliDateTimePicker fullWidth label="تاریخ شروع اعتبار" value={effectiveFrom} onChange={(value) => setEffectiveFrom(value ?? '')} helperText="در صورت خالی‌بودن، زمان فعلی ثبت می‌شود." /><TextField label="توضیحات اختیاری" multiline minRows={2} value={note} onChange={(e) => setNote(e.target.value)} /><Button variant="contained" disabled={!valid || create.isPending} onClick={() => setConfirmOpen(true)}>ثبت نرخ جدید</Button>{create.error && <Alert severity="error">{getApiErrorMessage(create.error, 'ثبت نرخ دلار انجام نشد.')}</Alert>}</Stack></Paper>}
    <Typography variant="h6" sx={{ mb: 1 }}>تاریخچه نرخ دلار</Typography>{history.isError && <Alert severity="error" action={<Button onClick={() => history.refetch()}>تلاش مجدد</Button>}>خطا در دریافت تاریخچه نرخ دلار</Alert>}<Paper><DataGrid autoHeight rows={history.data?.data ?? []} columns={columns} loading={history.isFetching} rowCount={history.data?.meta.total ?? 0} paginationMode="server" paginationModel={pagination} onPaginationModelChange={setPagination} pageSizeOptions={[10, 20, 50, 100]} disableRowSelectionOnClick localeText={{ noRowsLabel: 'هنوز سابقه‌ای برای نرخ دلار ثبت نشده است.' }} sx={{ border: 0, minHeight: 320 }} /></Paper>
    <Dialog open={confirmOpen} onClose={() => !create.isPending && setConfirmOpen(false)}><DialogTitle>تأیید ثبت نرخ جدید</DialogTitle><DialogContent><Alert severity="warning">با ثبت نرخ جدید، بازه نرخ فعلی بسته می‌شود و قیمت ریالی تمام محصولات دلاری مجدداً محاسبه خواهد شد. قیمت فروش‌ها و اسناد قبلی تغییر نمی‌کند.</Alert></DialogContent><DialogActions><Button onClick={() => setConfirmOpen(false)} disabled={create.isPending}>انصراف</Button><Button variant="contained" onClick={submit} disabled={create.isPending}>تأیید و ثبت</Button></DialogActions></Dialog>
  </PageContainer>;
}
