import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { opportunitiesService } from '../services/opportunities.service';
import type { CompanyOpportunityPayload, OpportunityListParams, OpportunityPayload, UpdateOpportunityPayload } from '../types/opportunity.types';

export const opportunityKeys = { all: ['opportunities'] as const, list: (p: OpportunityListParams) => ['opportunities', 'list', p] as const, company: (id: string, p?: OpportunityListParams) => ['company-opportunities', id, p] as const };
function useInvalidate(companyId?: string) { const client = useQueryClient(); return () => Promise.all([client.invalidateQueries({ queryKey: opportunityKeys.all }), client.invalidateQueries({ queryKey: ['pipeline'] }), client.invalidateQueries({ queryKey: ['company-opportunities', companyId] }), client.invalidateQueries({ queryKey: ['companies', 'detail', companyId] }), client.invalidateQueries({ queryKey: ['reports'] })]); }
export function useOpportunities(params: OpportunityListParams, enabled = true) { return useQuery({ queryKey: opportunityKeys.list(params), queryFn: () => opportunitiesService.list(params), placeholderData: keepPreviousData, enabled }); }
export function useCompanyOpportunities(companyId: string, params: OpportunityListParams, enabled = true) { return useQuery({ queryKey: opportunityKeys.company(companyId, params), queryFn: () => opportunitiesService.listByCompany(companyId, params), placeholderData: keepPreviousData, enabled }); }
export function useCreateOpportunity(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: (payload: OpportunityPayload | CompanyOpportunityPayload) => companyId ? opportunitiesService.createForCompany(companyId, payload as CompanyOpportunityPayload) : opportunitiesService.create(payload as OpportunityPayload), onSuccess: invalidate }); }
export function useUpdateOpportunity(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: ({ id, payload }: { id: string; payload: UpdateOpportunityPayload }) => opportunitiesService.update(id, payload), onSuccess: invalidate }); }
export function useChangeOpportunityStage(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: ({ id, stageId, note }: { id: string; stageId: string; note?: string }) => opportunitiesService.changeStage(id, stageId, note), onSuccess: invalidate }); }
export function useChangeOpportunityOwner(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: ({ id, ownerId }: { id: string; ownerId: string | null }) => opportunitiesService.changeOwner(id, ownerId), onSuccess: invalidate }); }
export function useArchiveOpportunity(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: ({ id, reason }: { id: string; reason?: string }) => opportunitiesService.archive(id, reason), onSuccess: invalidate }); }
export function useRestoreOpportunity(companyId?: string) { const invalidate = useInvalidate(companyId); return useMutation({ mutationFn: opportunitiesService.restore, onSuccess: invalidate }); }
