import { useState } from 'react';
import { toast } from 'sonner';
import { Alert, Button, Chip, Paper, Stack, Typography } from '@mui/material';
import { DataGrid, type GridColDef, type GridPaginationModel, type GridRenderCellParams } from '@mui/x-data-grid';
import { can } from '@/features/auth/utils/permissions';
import { useAuthStore } from '@/store/authStore';
import { getPriorityLabel } from '@/features/companies/utils/companyDisplay';
import { useArchiveOpportunity, useCompanyOpportunities, useRestoreOpportunity } from '../hooks/useOpportunities';
import type { Opportunity } from '../types/opportunity.types';
import OpportunityFormDialog from './OpportunityFormDialog';
import ChangeOpportunityStageDialog from './ChangeOpportunityStageDialog';
import ChangeOpportunityOwnerDialog from './ChangeOpportunityOwnerDialog';

export default function CompanyOpportunitiesTab({ companyId }: { companyId: string }) { const user = useAuthStore((s) => s.user); const allowed = can(user, 'opportunity:view'); const [page, setPage] = useState<GridPaginationModel>({ page: 0, pageSize: 10 }); const query = useCompanyOpportunities(companyId, { page: page.page + 1, limit: page.pageSize, includeArchived: true }, allowed); const [form, setForm] = useState<Opportunity | null | undefined>(undefined); const [stage, setStage] = useState<Opportunity | null>(null); const [owner, setOwner] = useState<Opportunity | null>(null); const archive = useArchiveOpportunity(companyId); const restore = useRestoreOpportunity(companyId);
  if (!allowed) return <Alert severity="warning">Ø¯Ø³ØªØ±Ø³ÛŒ Ù…Ø´Ø§Ù‡Ø¯Ù‡ ÙØ±ØµØªâ€ŒÙ‡Ø§ ÙØ¹Ø§Ù„ Ù†ÛŒØ³Øª.</Alert>;
  const archiveToggle = async (item: Opportunity) => { try { if (item.archivedAt) await restore.mutateAsync(item.id); else await archive.mutateAsync({ id: item.id }); toast.success(item.archivedAt ? 'ÙØ±ØµØª Ø¨Ø§Ø²ÛŒØ§Ø¨ÛŒ Ø´Ø¯.' : 'ÙØ±ØµØª Ø¨Ø§ÛŒÚ¯Ø§Ù†ÛŒ Ø´Ø¯.'); } catch { toast.error('Ø¹Ù…Ù„ÛŒØ§Øª Ø¨Ø§ÛŒÚ¯Ø§Ù†ÛŒ ÙØ±ØµØª Ø§Ù†Ø¬Ø§Ù… Ù†Ø´Ø¯.'); } };
  const columns: GridColDef<Opportunity>[] = [{ field: 'title', headerName: 'Ø¹Ù†ÙˆØ§Ù† ÙØ±ØµØª', minWidth: 200, flex: 1 }, { field: 'stage', headerName: 'Ù…Ø±Ø­Ù„Ù‡', minWidth: 140, valueGetter: (_v, r) => r.stage?.label ?? 'â€”' }, { field: 'owner', headerName: 'Ù…Ø§Ù„Ú©', minWidth: 140, valueGetter: (_v, r) => r.owner?.fullName ?? 'â€”' }, { field: 'priority', headerName: 'Ø§ÙˆÙ„ÙˆÛŒØª', minWidth: 100, valueFormatter: (v) => getPriorityLabel(v) }, { field: 'archivedAt', headerName: 'ÙˆØ¶Ø¹ÛŒØª', minWidth: 100, renderCell: ({ row }) => <Chip size="small" color={row.archivedAt ? 'default' : 'success'} label={row.archivedAt ? 'Ø¨Ø§ÛŒÚ¯Ø§Ù†ÛŒ' : 'ÙØ¹Ø§Ù„'} /> }, { field: 'actions', headerName: 'Ø¹Ù…Ù„ÛŒØ§Øª', minWidth: 390, sortable: false, renderCell: ({ row }: GridRenderCellParams<Opportunity>) => <Stack direction="row"><Button size="small" disabled={!can(user, 'opportunity:update') || Boolean(row.archivedAt)} onClick={() => setForm(row)}>ÙˆÛŒØ±Ø§ÛŒØ´</Button><Button size="small" disabled={!can(user, 'opportunity:change-stage') || Boolean(row.archivedAt)} onClick={() => setStage(row)}>Ù…Ø±Ø­Ù„Ù‡</Button><Button size="small" disabled={!can(user, 'opportunity:change-owner') || Boolean(row.archivedAt)} onClick={() => setOwner(row)}>Ù…Ø§Ù„Ú©</Button><Button size="small" color="warning" disabled={!can(user, row.archivedAt ? 'opportunity:restore' : 'opportunity:archive')} onClick={() => archiveToggle(row)}>{row.archivedAt ? 'Ø¨Ø§Ø²ÛŒØ§Ø¨ÛŒ' : 'Ø¨Ø§ÛŒÚ¯Ø§Ù†ÛŒ'}</Button></Stack> }];
  return <><Stack direction="row" sx={{ justifyContent: 'space-between', mb: 2 }}><Typography variant="h6">ÙØ±ØµØªâ€ŒÙ‡Ø§ÛŒ Ø´Ø±Ú©Øª</Typography>{can(user, 'opportunity:create') && <Button variant="contained" onClick={() => setForm(null)}>Ø§ÛŒØ¬Ø§Ø¯ ÙØ±ØµØª</Button>}</Stack>{query.isError && <Alert severity="error" sx={{ mb: 2 }}>Ø¯Ø±ÛŒØ§ÙØª ÙØ±ØµØªâ€ŒÙ‡Ø§ Ø§Ù†Ø¬Ø§Ù… Ù†Ø´Ø¯.</Alert>}<Paper><DataGrid autoHeight rows={query.data?.data ?? []} columns={columns} loading={query.isFetching} rowCount={query.data?.meta.total ?? 0} paginationMode="server" paginationModel={page} onPaginationModelChange={setPage} pageSizeOptions={[5, 10, 20]} disableRowSelectionOnClick /></Paper>{form !== undefined && <OpportunityFormDialog companyId={companyId} opportunity={form} open onClose={() => setForm(undefined)} />}{stage && <ChangeOpportunityStageDialog opportunity={stage} open onClose={() => setStage(null)} />}{owner && <ChangeOpportunityOwnerDialog opportunity={owner} open onClose={() => setOwner(null)} />}</>;
}

